[tool.black]
target-version = ['py38']
exclude = '''
/(
    \.eggs
  | \.git
  | \.mypy_cache
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | generated
	| wrapper
  | __init__\.pyi
)/
'''

[tool.isort]
profile = "black"
src_paths="."
skip_glob = ["generated", "__init__.pyi"]
