[tool.black]
target-version = ['py38']
exclude = '''
/(
    \.eggs
  | \.git
  | \.mypy_cache
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | generated
	| wrapper
  | __init__\.pyi
)/
'''

# [tool.isort]
# profile = "black"
# src_paths="."
# skip_glob = ["generated", "__init__.pyi"]

# [tool.flake8]
# exclude = [
#   "__pycache__",
#   "generated",
#   "wrapper",
# ]
# # ignore = E501, W503, B008, B028
# ignore = [
#   "E501",  # line too long
#   "W503",  # line break before binary operator
#   "B008",  # do not perform function calls in argument defaults
#   "B028",  # do not use bare except
# ]
# max-complexity = 10

[tool.ruff]
unfixable = []
exclude = [
  "__pycache__",
  "generated",
  "wrapper",
]
ignore = [
  "B008",  # do not perform function calls in argument defaults
  "B904",  # TODO only temporary. should be fixed.
  "E501",  # line too long
  "N815",  # mixedCase variable in class scope
  "N803",  # argument name should be lowercase
  "N806",  # variable in function should be lowercase
  "N812",  # lowercase imported as non lowercase
  "N999",  # Invalid module name: 'Browser'
  "PLR0913",  # too many arguments
]
select = [
  "E",
  "F",
  "W",
  "C90",
  "I",
  "N",
  "B",
  "PYI",
  "PL",
  "PTH",
  "UP",
  "A",
  "C4",
  "DTZ",
  "ISC",
  "ICN",
  "INP",
  "PIE",
  "T20",
  "PYI",
  "PT",
  "RSE",
  "RET",
  "SIM",
  "TID"
]
