[tool.black]
target-version = ['py38']
exclude = '''
/(
    \.eggs
  | \.git
  | \.mypy_cache
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | generated
	| wrapper
  | browser\.pyi
)/
'''

[tool.ruff]
line-length = 120
unfixable = []
exclude = [
  "__pycache__",
  "generated",
  "wrapper",
  "browser.pyi",
]
ignore = [
  "B008",  # do not perform function calls in argument defaults
  "B904",  # TODO only temporary. should be fixed.
  "E501",  # line too long
  "N815",  # mixedCase variable in class scope
  "N803",  # argument name should be lowercase
  "N806",  # variable in function should be lowercase
  "N812",  # lowercase imported as non lowercase
  "N999",  # Invalid module name: 'Browser'
  "PLR0913",  # too many arguments
  "UP007",    # No `X | Y` for type annotation in py28
]
target-version = "py38"
select = [
  "E",
  "F",
  "W",
  "C90",
  "I",
  "N",
  "B",
  "PYI",
  "PL",
  "PTH",
  "UP",
  "A",
  "C4",
  "DTZ",
  "ISC",
  "ICN",
  "INP",
  "PIE",
  "T20",
  "PYI",
  "PT",
  "RSE",
  "RET",
  "SIM",
  "RUF",
  "ASYNC",
  "DTZ",
  "FA",
  "PERF",
]
