[tool.ruff]
lint.unfixable = []
exclude = [
  "__pycache__",
  "generated",
  "wrapper",
  "browser.pyi",
]
lint.ignore = [
  "B008",  # do not perform function calls in argument defaults
  "B904",  # TODO only temporary. should be fixed.
  "E501",  # line too long
  "N815",  # mixedCase variable in class scope
  "N803",  # argument name should be lowercase
  "N806",  # variable in function should be lowercase
  "N812",  # lowercase imported as non lowercase
  "N999",  # Invalid module name: 'Browser'
  "PLR0913",  # too many arguments
]
target-version = "py39"
lint.select = [
  "E",
  "F",
  "W",
  "C90",
  "I",
  "N",
  "B",
  "PYI",
  "PL",
  "PTH",
  "UP",
  "A",
  "C4",
  "DTZ",
  "ISC",
  "ICN",
  "INP",
  "PIE",
  "T20",
  "PYI",
  "PT",
  "RSE",
  "RET",
  "SIM",
  "RUF"
]
[tool.ruff.lint.per-file-ignores]
"tasks.py" = [
  "T201",
  "PTH123",
  "PTH120"
]
"bootstrap.py" = ["T201"]

[tool.robotidy]
src = ["atest"]
lineseparator = "unix"
configure = [
  "NormalizeAssignments:equal_sign_type=space_and_equal_sign",
  "NormalizeAssignments:equal_sign_type_variables=space_and_equal_sign",
  "NormalizeNewLines:section_lines=1",
  "RenameKeywords:enabled=True",
  "RenameTestCases:capitalize_each_word=True:enabled=True"
]
