tasks:
  - init: |
      pip install robotframework
    command: |
      python -m pip install --upgrade pip
      pip install -r Browser/dev-requirements.txt
      pip install -r pyproject.toml
      inv deps --system
      npx --yes playwright install-deps
      inv build
image: gitpod/workspace-full-vnc
ports:
  - port: 6080
    onOpen: open-preview
vscode:
  extensions:
    - ms-python.python
    - d-biehl.robotcode
    - eamodio.gitlens
    - dbaeumer.vscode-eslint
    - ms-python.debugpy
