FROM mcr.microsoft.com/playwright:v1.56.0-noble

# Update apt-get
USER root
RUN apt-get update
RUN python3 --version
RUN apt install -y python3-pip python3.12-venv

# Clean up
USER root
RUN apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Set environment variables
ENV PATH="/home/pwuser/.local/bin:${PATH}"
ENV NODE_PATH=/usr/lib/node_modules

# Cache operations
USER root
RUN mv /root/.cache/ /home/pwuser/.cache || true
RUN chmod a+rwx -R /home/pwuser/.cache || true

# Switch to pwuser for the remaining operations
USER pwuser

# Create venv and active it
RUN python3 -m venv /home/pwuser/.venv
ENV PATH="/home/pwuser/.venv/bin:$PATH"

# Upgrade pip and wheel for the user
RUN pip3 install --no-cache-dir --upgrade pip wheel uv

# Copy the dist files
COPY docker/dist/*.whl /home/pwuser/
# Install RobotFramework and Browser library
RUN uv pip install --no-cache-dir --upgrade robotframework && \
    uv pip install --no-cache-dir /home/pwuser/robotframework_browser-*.whl && \
    rm /home/pwuser/*.whl

# Initialize Browser library without browsers binaries
RUN rfbrowser init --skip-browsers

# Install development dependencies
RUN uv pip install --no-cache-dir --upgrade \
    robotframework-pabot \
    robotstatuschecker \
    Pillow \
    python-dateutil \
    robotframework-crypto \
    robotframework-archivelibrary \
    cryptography
