// Copyright 2020-     Robot Framework Foundation
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import { BrowserContext } from 'playwright-core';

import { logger } from './browser_logger';
import * as pb from './generated/playwright';
import { exists } from './playwright-invoke';
import { emptyWithLog } from './response-util';

export async function createCredential(
    request: pb.Request_CreateCredential,
    context?: BrowserContext,
): Promise<pb.Response_Empty> {
    exists(context, 'Tried to create credential, no open context');
    const { rpId, id, privateKey, publicKey, userHandle } = request;
    const options: any = {};
    let logMessage = `Create credential with rpId: ${rpId}`;
    if (id !== 'ROBOT_FRAMEWORK_BROWSER_NO_SET') {
        options.id = id;
        logMessage += `, id: ${id}`;
    } else {
        logMessage += `, id: <auto-generated>`;
    }
    if (privateKey !== 'ROBOT_FRAMEWORK_BROWSER_NO_SET') {
        options.privateKey = privateKey;
    }
    if (publicKey !== 'ROBOT_FRAMEWORK_BROWSER_NO_SET') {
        options.publicKey = publicKey;
    }
    if (userHandle !== 'ROBOT_FRAMEWORK_BROWSER_NO_SET') {
        options.userHandle = userHandle;
    }
    logger.info(logMessage);
    await context.credentials.create(rpId, options);
    logger.info(`Install credential.`);
    await context.credentials.install();
    return emptyWithLog(logMessage + ` and installed it successfully.`);
}

export async function installCredential(context?: BrowserContext): Promise<pb.Response_Empty> {
    exists(context, 'Tried to install credential, no open context');
    await context.credentials.install();
    return emptyWithLog(`Installed empty credentials for the active context.`);
}

export async function getCredential(
    request: pb.Request_CredentialIdAndRpId,
    context?: BrowserContext,
): Promise<pb.Response_GetCredential> {
    exists(context, 'Tried to get credential, no open context');
    const options: any = {};
    const { id, rpId } = request;
    if (id !== 'ROBOT_FRAMEWORK_BROWSER_NO_SET') {
        logger.info(`Get credential with id: ${id}`);
        options.id = id;
    }
    if (rpId !== 'ROBOT_FRAMEWORK_BROWSER_NO_SET') {
        logger.info(`Get credential with rpId: ${rpId}`);
        options.rpId = rpId;
    }
    const [credential] = await context.credentials.get(options);
    logger.info(`Retrieved credential with id: ${JSON.stringify(credential)}`);
    return {
        id: credential.id,
        rpId: credential.rpId,
        userHandle: credential.userHandle,
        privateKey: credential.privateKey,
        publicKey: credential.publicKey,
        log: `Retrieved credential successfully with id: ${credential.id}`,
    };
}

export async function deleteCredential(
    request: pb.Request_CredentialIdAndRpId,
    context?: BrowserContext,
): Promise<pb.Response_Empty> {
    exists(context, 'Tried to delete credential, no open context');
    const id = request.id;
    logger.info(`Delete credential with id: ${id}`);
    await context.credentials.delete(id);
    return emptyWithLog(`Deleted credential successfully with id: ${id}`);
}
