name: auto-merge

# Modified from https://github.com/JabRef/JabRef-Browser-Extension/blob/56666f241f3767af28fe2afb49b36afbf30bfb14/.github/workflows/automerge.yml#L22-L41
on:
  pull_request:
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}

jobs:
  automerge:
    name: Automerge Dependabot
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    needs: test-install
    steps:
      - name: 'Wait for status checks'
        id: waitforstatuschecks
        uses: "WyriHaximus/github-action-wait-for-status@v1.2"
        with:
          ignoreActions: Automerge Dependabot
          checkInterval: 13
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - name: Merge pull requests
        uses: pascalgn/automerge-action@v0.12.0
        if: steps.waitforstatuschecks.outputs.status == 'success'
        env:
          MERGE_METHOD: "squash"
          MERGE_LABELS: ""
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
