name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target-platform: linux-x86_64
          - os: ubuntu-latest
            target-platform: linux-aarch64
          - os: windows-latest
            target-platform: win-64
          - os: windows-11-arm
          - os: macos-latest
            target-platform: osx-intel
          - os: macos-latest
            target-platform: osx-arm64

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        if: matrix.os != 'windows-11-arm'
        run: |
          python -m pip install --upgrade pip
          pip install uv
          uv pip install wheel invoke --python 3.13  --system --verbose
          python -c "import sys;print(sys.platform)"
          python -c "import sysconfig;print(sysconfig.get_platform())"
          python -c "import platform;print(platform.machine().lower())"
          inv deps
      - name: Install dependencies on windows-11-arm
        if: matrix.os == 'windows-11-arm'
        run: |
          python -m pip install --upgrade pip
          pip install wheel invoke
          python -c "import sys;print(sys.platform)"
          python -c "import sysconfig;print(sysconfig.get_platform())"
          python -c "import platform;print(platform.machine().lower())"
          inv deps
      - name: Build wheels
        run: |
          inv package-nodejs
          inv foo
      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: browser_batteries/dist/*.whl
          if-no-files-found: error
