name: manuals
on: 
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-docker-image:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Set up Python 3.9
          uses: actions/setup-python@v4
          with:
            python-version: 3.9
            cache: 'pip'
        - name: Install python dependencies
          run: |
            python -m pip install --upgrade pip
            pip install wheel
            pip install -r Browser/dev-requirements.txt
        - name: Install invoke deps
          run: |
            invoke deps
        - name: Run tests with latest stable docker image
          run: invoke docker-test
