name: manuals
on: 
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-docker-image:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Set up Python 3.9
          uses: actions/setup-python@v4
          with:
            python-version: 3.9
            cache: 'pip'
        - name: Install python dependencies
          run: |
            python -m pip install --upgrade pip
            pip install wheel
            pip install -r Browser/dev-requirements.txt
        - name: Install invoke deps
          run: invoke deps
        - name: build testing docker image
          run: invoke docker-tester
        - name: set permissions
          run: chmod -R 777 atest/
        - name: Run tests with latest stable docker image
          run: |
            invoke docker-test
            returnval=$?
            # If there are more than 10 failures fail the github action.
            if [[ returnval -gt 10]]; then exit $returnval; else exit 0; fi
